services:
  php:
    build: ./
    restart: on-failure
    volumes:
      - ./:/var/www/
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=only
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data_only:/var/lib/mysql

volumes:
  db_data_only:
